apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app-container
          image: nathanirahul/student-performance-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001
